BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE "user"';
	EXECUTE IMMEDIATE 'DROP TABLE "message"';
	EXECUTE IMMEDIATE 'DROP TABLE "faculty"';
	EXECUTE IMMEDIATE 'DROP TABLE "school"';
	EXECUTE IMMEDIATE 'DROP TABLE "edit"';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -942 THEN
			RAISE;
		END IF;
END;

CREATE TABLE "user" (
	"id" INT GENERATED AS IDENTITY NOT NULL PRIMARY KEY,
	"name" VARCHAR2(100) NOT NULL,
	"email" VARCHAR2(100) NOT NULL,
	"password" VARCHAR2(100) NOT NULL,
	"description" VARCHAR2(4000)
);

CREATE TABLE "school" (
	"id" INT GENERATED AS IDENTITY NOT NULL PRIMARY KEY,
	"name" VARCHAR2(100) NOT NULL,
	"description" VARCHAR2(4000),
	"location" SDO_GEO_ADDR
);

CREATE TABLE "faculty" (
	"id" INT GENERATED AS IDENTITY NOT NULL PRIMARY KEY,
	"name" VARCHAR2(100) NOT NULL,
	"description" VARCHAR2(4000),
	"location" SDO_GEO_ADDR,
	"school_id" INT NOT NULL,
	CONSTRAINT "school_id_fk" FOREIGN KEY ("school_id") REFERENCES "school" ("id") ON DELETE CASCADE
);

CREATE TABLE "message" (
	"id" INT GENERATED AS IDENTITY NOT NULL PRIMARY KEY,
	"title" VARCHAR2(100) NOT NULL,
	"text" VARCHAR2(4000),
	"creation_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"valid_from" TIMESTAMP,
	"valid_to" TIMESTAMP,
	"school_id" INT,
	"faculty_id" INT,
	CONSTRAINT "school_id_fk2" FOREIGN KEY ("school_id") REFERENCES "school" ("id") ON DELETE CASCADE,
	CONSTRAINT "faculty_id_fk" FOREIGN KEY ("faculty_id") REFERENCES "faculty" ("id") ON DELETE CASCADE
);

CREATE TABLE "edit" (
	"id" INT GENERATED AS IDENTITY NOT NULL PRIMARY KEY,
	"timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"changes" VARCHAR2(4000) NOT NULL,
	"message_id" INT NOT NULL,
	CONSTRAINT "message_id_fk" FOREIGN KEY ("message_id") REFERENCES "message" ("id") ON DELETE CASCADE
)
